### ISSUE TITLE
Server sided Notify events are incorrectly formatted

### ISSUE THREAD

**Issue by blazeitjames** [The-Kodah/kodek-fakeid#1]
Therefore, if I don't have the cash needed to make an ID, there will be no error message.

Proper notify usage on the server: `exports.qbx_core:Notify(source, text, notifyType, duration, subTitle, notifyPosition, notifyStyle, notifyIcon, notifyIconColor)`

**Comment by The-Kodah** [comment]
Thank you, I have fixed this with v1.2.0

**Comment by The-Kodah** [comment]
Thank you, I have fixed this with v1.2.0
